# Generated by Django 6.0 on 2026-01-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='canjeado',
            field=models.BooleanField(default=False, verbose_name='Producto Canjeado'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='fecha_canje',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Canje'),
        ),
    ]
